/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/accommodationMappers";
import * as Parameters from "../models/parameters";
import { GalaxyApiContext } from "../galaxyApiContext";

/** Class representing a Accommodation. */
export class Accommodation {
  private readonly client: GalaxyApiContext;

  /**
   * Create a Accommodation.
   * @param {GalaxyApiContext} client Reference to the service client.
   */
  constructor(client: GalaxyApiContext) {
    this.client = client;
  }

  /**
   * @summary Get list of accomodations that could be available from the specified point of sales,
   * with full details about it
   * @param pointOfSalesId The point of sales identifier.
   * @param pageSize Size of the page.
   * @param page The page, starting at 0.
   * @param acceptLanguage The culture you wish to get data in, api/content/language can provide
   * valid cultures.
   * @param [options] The optional parameters
   * @returns Promise<Models.AccommodationGetPagedResponse>
   */
  getPaged(pointOfSalesId: number, pageSize: number, page: number, acceptLanguage: string, options?: msRest.RequestOptionsBase): Promise<Models.AccommodationGetPagedResponse>;
  /**
   * @param pointOfSalesId The point of sales identifier.
   * @param pageSize Size of the page.
   * @param page The page, starting at 0.
   * @param acceptLanguage The culture you wish to get data in, api/content/language can provide
   * valid cultures.
   * @param callback The callback
   */
  getPaged(pointOfSalesId: number, pageSize: number, page: number, acceptLanguage: string, callback: msRest.ServiceCallback<Models.GalaxyApiModelsSharedPagedResultGalaxyApiModelsAccommodationAccommodationDetails>): void;
  /**
   * @param pointOfSalesId The point of sales identifier.
   * @param pageSize Size of the page.
   * @param page The page, starting at 0.
   * @param acceptLanguage The culture you wish to get data in, api/content/language can provide
   * valid cultures.
   * @param options The optional parameters
   * @param callback The callback
   */
  getPaged(pointOfSalesId: number, pageSize: number, page: number, acceptLanguage: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.GalaxyApiModelsSharedPagedResultGalaxyApiModelsAccommodationAccommodationDetails>): void;
  getPaged(pointOfSalesId: number, pageSize: number, page: number, acceptLanguage: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.GalaxyApiModelsSharedPagedResultGalaxyApiModelsAccommodationAccommodationDetails>, callback?: msRest.ServiceCallback<Models.GalaxyApiModelsSharedPagedResultGalaxyApiModelsAccommodationAccommodationDetails>): Promise<Models.AccommodationGetPagedResponse> {
    return this.client.sendOperationRequest(
      {
        pointOfSalesId,
        pageSize,
        page,
        acceptLanguage,
        options
      },
      getPagedOperationSpec,
      callback) as Promise<Models.AccommodationGetPagedResponse>;
  }

  /**
   * @summary View one accomodation with full details
   * @param pointOfSalesId The point of sales identifier.
   * @param productId The product identifier.
   * @param acceptLanguage The culture you wish to get data in, api/content/language can provide
   * valid cultures.
   * @param [options] The optional parameters
   * @returns Promise<Models.AccommodationViewResponse>
   */
  view(pointOfSalesId: number, productId: string, acceptLanguage: string, options?: msRest.RequestOptionsBase): Promise<Models.AccommodationViewResponse>;
  /**
   * @param pointOfSalesId The point of sales identifier.
   * @param productId The product identifier.
   * @param acceptLanguage The culture you wish to get data in, api/content/language can provide
   * valid cultures.
   * @param callback The callback
   */
  view(pointOfSalesId: number, productId: string, acceptLanguage: string, callback: msRest.ServiceCallback<Models.GalaxyApiModelsAccommodationAccommodationDetails>): void;
  /**
   * @param pointOfSalesId The point of sales identifier.
   * @param productId The product identifier.
   * @param acceptLanguage The culture you wish to get data in, api/content/language can provide
   * valid cultures.
   * @param options The optional parameters
   * @param callback The callback
   */
  view(pointOfSalesId: number, productId: string, acceptLanguage: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.GalaxyApiModelsAccommodationAccommodationDetails>): void;
  view(pointOfSalesId: number, productId: string, acceptLanguage: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.GalaxyApiModelsAccommodationAccommodationDetails>, callback?: msRest.ServiceCallback<Models.GalaxyApiModelsAccommodationAccommodationDetails>): Promise<Models.AccommodationViewResponse> {
    return this.client.sendOperationRequest(
      {
        pointOfSalesId,
        productId,
        acceptLanguage,
        options
      },
      viewOperationSpec,
      callback) as Promise<Models.AccommodationViewResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const getPagedOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "v3/api/accommodation/{pointOfSalesId}/{pageSize}/{page}",
  urlParameters: [
    Parameters.pointOfSalesId,
    Parameters.pageSize,
    Parameters.page
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.GalaxyApiModelsSharedPagedResultGalaxyApiModelsAccommodationAccommodationDetails
    },
    default: {}
  },
  serializer
};

const viewOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "v3/api/accommodation/view/{pointOfSalesId}/{productId}",
  urlParameters: [
    Parameters.pointOfSalesId,
    Parameters.productId
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.GalaxyApiModelsAccommodationAccommodationDetails
    },
    default: {}
  },
  serializer
};
