/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/basketAddMappers";
import * as Parameters from "../models/parameters";
import { GalaxyApiContext } from "../galaxyApiContext";

/** Class representing a BasketAdd. */
export class BasketAdd {
  private readonly client: GalaxyApiContext;

  /**
   * Create a BasketAdd.
   * @param {GalaxyApiContext} client Reference to the service client.
   */
  constructor(client: GalaxyApiContext) {
    this.client = client;
  }

  /**
   * @summary Add accommodation to the specified basket. It is using the searchId and bookKey
   * combination to identify which result that should be added.
   * @param basketId The basket identifier.
   * @param searchId The availibility search.
   * @param bookKey The key of the item you wish to add.
   * @param [options] The optional parameters
   * @returns Promise<Models.BasketAddPutAccommodationInBasketResponse>
   */
  putAccommodationInBasket(basketId: number, searchId: string, bookKey: string, options?: msRest.RequestOptionsBase): Promise<Models.BasketAddPutAccommodationInBasketResponse>;
  /**
   * @param basketId The basket identifier.
   * @param searchId The availibility search.
   * @param bookKey The key of the item you wish to add.
   * @param callback The callback
   */
  putAccommodationInBasket(basketId: number, searchId: string, bookKey: string, callback: msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityBasketBasketAddResult>): void;
  /**
   * @param basketId The basket identifier.
   * @param searchId The availibility search.
   * @param bookKey The key of the item you wish to add.
   * @param options The optional parameters
   * @param callback The callback
   */
  putAccommodationInBasket(basketId: number, searchId: string, bookKey: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityBasketBasketAddResult>): void;
  putAccommodationInBasket(basketId: number, searchId: string, bookKey: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityBasketBasketAddResult>, callback?: msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityBasketBasketAddResult>): Promise<Models.BasketAddPutAccommodationInBasketResponse> {
    return this.client.sendOperationRequest(
      {
        basketId,
        searchId,
        bookKey,
        options
      },
      putAccommodationInBasketOperationSpec,
      callback) as Promise<Models.BasketAddPutAccommodationInBasketResponse>;
  }

  /**
   * @summary Add accommodation from a fuzzy search to a specified basket. It is using the searchId
   * and bookKey combination to identify which result that should be added.
   * @param basketId The basket identifier.
   * @param searchId The search identifier.
   * @param bookKey The key of the item you wish to add.
   * @param [options] The optional parameters
   * @returns Promise<Models.BasketAddPutFuzzyAccommodationInBasketResponse>
   */
  putFuzzyAccommodationInBasket(basketId: number, searchId: string, bookKey: number, options?: Models.BasketAddPutFuzzyAccommodationInBasketOptionalParams): Promise<Models.BasketAddPutFuzzyAccommodationInBasketResponse>;
  /**
   * @param basketId The basket identifier.
   * @param searchId The search identifier.
   * @param bookKey The key of the item you wish to add.
   * @param callback The callback
   */
  putFuzzyAccommodationInBasket(basketId: number, searchId: string, bookKey: number, callback: msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityBasketBasketAddResult>): void;
  /**
   * @param basketId The basket identifier.
   * @param searchId The search identifier.
   * @param bookKey The key of the item you wish to add.
   * @param options The optional parameters
   * @param callback The callback
   */
  putFuzzyAccommodationInBasket(basketId: number, searchId: string, bookKey: number, options: Models.BasketAddPutFuzzyAccommodationInBasketOptionalParams, callback: msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityBasketBasketAddResult>): void;
  putFuzzyAccommodationInBasket(basketId: number, searchId: string, bookKey: number, options?: Models.BasketAddPutFuzzyAccommodationInBasketOptionalParams | msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityBasketBasketAddResult>, callback?: msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityBasketBasketAddResult>): Promise<Models.BasketAddPutFuzzyAccommodationInBasketResponse> {
    return this.client.sendOperationRequest(
      {
        basketId,
        searchId,
        bookKey,
        options
      },
      putFuzzyAccommodationInBasketOperationSpec,
      callback) as Promise<Models.BasketAddPutFuzzyAccommodationInBasketResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const putAccommodationInBasketOperationSpec: msRest.OperationSpec = {
  httpMethod: "PUT",
  path: "v3/api/basket/add/accommodation/{basketId}/{searchId}/{bookKey}",
  urlParameters: [
    Parameters.basketId,
    Parameters.searchId,
    Parameters.bookKey0
  ],
  responses: {
    200: {
      bodyMapper: Mappers.GalaxyApiModelsAvailabilityBasketBasketAddResult
    },
    default: {}
  },
  serializer
};

const putFuzzyAccommodationInBasketOperationSpec: msRest.OperationSpec = {
  httpMethod: "PUT",
  path: "v3/api/basket/add/accommodation/fuzzy/{basketId}/{searchId}/{bookKey}",
  urlParameters: [
    Parameters.basketId,
    Parameters.searchId,
    Parameters.bookKey1
  ],
  queryParameters: [
    Parameters.personConfigadults,
    Parameters.personConfigchildrenAges
  ],
  responses: {
    200: {
      bodyMapper: Mappers.GalaxyApiModelsAvailabilityBasketBasketAddResult
    },
    default: {}
  },
  serializer
};
