/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/fuzzyAccommodationSearchMappers";
import * as Parameters from "../models/parameters";
import { GalaxyApiContext } from "../galaxyApiContext";

/** Class representing a FuzzyAccommodationSearch. */
export class FuzzyAccommodationSearch {
  private readonly client: GalaxyApiContext;

  /**
   * Create a FuzzyAccommodationSearch.
   * @param {GalaxyApiContext} client Reference to the service client.
   */
  constructor(client: GalaxyApiContext) {
    this.client = client;
  }

  /**
   * @summary Scans the specified point of sales.
   * @param search The search.
   * @param acceptLanguage The culture you wish to get data in, api/content/language can provide
   * valid cultures.
   * @param [options] The optional parameters
   * @returns Promise<Models.FuzzyAccommodationSearchScanResponse>
   */
  scan(search: Models.GalaxyApiModelsAvailabilityFuzzyAccommodationFuzzyAccommodationSearchFilter, acceptLanguage: string, options?: msRest.RequestOptionsBase): Promise<Models.FuzzyAccommodationSearchScanResponse>;
  /**
   * @param search The search.
   * @param acceptLanguage The culture you wish to get data in, api/content/language can provide
   * valid cultures.
   * @param callback The callback
   */
  scan(search: Models.GalaxyApiModelsAvailabilityFuzzyAccommodationFuzzyAccommodationSearchFilter, acceptLanguage: string, callback: msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityFuzzyAccommodationFuzzyAccommodationSearchScanResult>): void;
  /**
   * @param search The search.
   * @param acceptLanguage The culture you wish to get data in, api/content/language can provide
   * valid cultures.
   * @param options The optional parameters
   * @param callback The callback
   */
  scan(search: Models.GalaxyApiModelsAvailabilityFuzzyAccommodationFuzzyAccommodationSearchFilter, acceptLanguage: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityFuzzyAccommodationFuzzyAccommodationSearchScanResult>): void;
  scan(search: Models.GalaxyApiModelsAvailabilityFuzzyAccommodationFuzzyAccommodationSearchFilter, acceptLanguage: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityFuzzyAccommodationFuzzyAccommodationSearchScanResult>, callback?: msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityFuzzyAccommodationFuzzyAccommodationSearchScanResult>): Promise<Models.FuzzyAccommodationSearchScanResponse> {
    return this.client.sendOperationRequest(
      {
        search,
        acceptLanguage,
        options
      },
      scanOperationSpec,
      callback) as Promise<Models.FuzzyAccommodationSearchScanResponse>;
  }

  /**
   * @summary Retrieve an already done fuzzy accommodation scan
   * @param query
   * @param acceptLanguage The culture you wish to get data in, api/content/language can provide
   * valid cultures.
   * @param [options] The optional parameters
   * @returns Promise<Models.FuzzyAccommodationSearchGetSearchResponse>
   */
  getSearch(query: Models.GalaxyApiModelsSharedQueryExistingSearchQuery, acceptLanguage: string, options?: msRest.RequestOptionsBase): Promise<Models.FuzzyAccommodationSearchGetSearchResponse>;
  /**
   * @param query
   * @param acceptLanguage The culture you wish to get data in, api/content/language can provide
   * valid cultures.
   * @param callback The callback
   */
  getSearch(query: Models.GalaxyApiModelsSharedQueryExistingSearchQuery, acceptLanguage: string, callback: msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityFuzzyAccommodationFuzzyAccommodationSearchScanResult>): void;
  /**
   * @param query
   * @param acceptLanguage The culture you wish to get data in, api/content/language can provide
   * valid cultures.
   * @param options The optional parameters
   * @param callback The callback
   */
  getSearch(query: Models.GalaxyApiModelsSharedQueryExistingSearchQuery, acceptLanguage: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityFuzzyAccommodationFuzzyAccommodationSearchScanResult>): void;
  getSearch(query: Models.GalaxyApiModelsSharedQueryExistingSearchQuery, acceptLanguage: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityFuzzyAccommodationFuzzyAccommodationSearchScanResult>, callback?: msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityFuzzyAccommodationFuzzyAccommodationSearchScanResult>): Promise<Models.FuzzyAccommodationSearchGetSearchResponse> {
    return this.client.sendOperationRequest(
      {
        query,
        acceptLanguage,
        options
      },
      getSearchOperationSpec,
      callback) as Promise<Models.FuzzyAccommodationSearchGetSearchResponse>;
  }

  /**
   * @summary Gets the arrival dates.
   * @param searchId The search identifier.
   * @param bookKey The key representing a scan result item.
   * @param firstArrival The first arrival.
   * @param lastArrival The last arrival.
   * @param [options] The optional parameters
   * @returns Promise<Models.FuzzyAccommodationSearchGetArrivalDatesResponse>
   */
  getArrivalDates(searchId: string, bookKey: string, firstArrival: Date | string, lastArrival: Date | string, options?: Models.FuzzyAccommodationSearchGetArrivalDatesOptionalParams): Promise<Models.FuzzyAccommodationSearchGetArrivalDatesResponse>;
  /**
   * @param searchId The search identifier.
   * @param bookKey The key representing a scan result item.
   * @param firstArrival The first arrival.
   * @param lastArrival The last arrival.
   * @param callback The callback
   */
  getArrivalDates(searchId: string, bookKey: string, firstArrival: Date | string, lastArrival: Date | string, callback: msRest.ServiceCallback<Date[] | string[]>): void;
  /**
   * @param searchId The search identifier.
   * @param bookKey The key representing a scan result item.
   * @param firstArrival The first arrival.
   * @param lastArrival The last arrival.
   * @param options The optional parameters
   * @param callback The callback
   */
  getArrivalDates(searchId: string, bookKey: string, firstArrival: Date | string, lastArrival: Date | string, options: Models.FuzzyAccommodationSearchGetArrivalDatesOptionalParams, callback: msRest.ServiceCallback<Date[] | string[]>): void;
  getArrivalDates(searchId: string, bookKey: string, firstArrival: Date | string, lastArrival: Date | string, options?: Models.FuzzyAccommodationSearchGetArrivalDatesOptionalParams | msRest.ServiceCallback<Date[] | string[]>, callback?: msRest.ServiceCallback<Date[] | string[]>): Promise<Models.FuzzyAccommodationSearchGetArrivalDatesResponse> {
    return this.client.sendOperationRequest(
      {
        searchId,
        bookKey,
        firstArrival,
        lastArrival,
        options
      },
      getArrivalDatesOperationSpec,
      callback) as Promise<Models.FuzzyAccommodationSearchGetArrivalDatesResponse>;
  }

  /**
   * @summary Gets the departure dates.
   * @param searchId The search identifier.
   * @param bookKey The key representing a scan result item.
   * @param arrival The arrival.
   * @param [options] The optional parameters
   * @returns Promise<Models.FuzzyAccommodationSearchGetDepartureDatesResponse>
   */
  getDepartureDates(searchId: string, bookKey: string, arrival: Date | string, options?: Models.FuzzyAccommodationSearchGetDepartureDatesOptionalParams): Promise<Models.FuzzyAccommodationSearchGetDepartureDatesResponse>;
  /**
   * @param searchId The search identifier.
   * @param bookKey The key representing a scan result item.
   * @param arrival The arrival.
   * @param callback The callback
   */
  getDepartureDates(searchId: string, bookKey: string, arrival: Date | string, callback: msRest.ServiceCallback<Date[] | string[]>): void;
  /**
   * @param searchId The search identifier.
   * @param bookKey The key representing a scan result item.
   * @param arrival The arrival.
   * @param options The optional parameters
   * @param callback The callback
   */
  getDepartureDates(searchId: string, bookKey: string, arrival: Date | string, options: Models.FuzzyAccommodationSearchGetDepartureDatesOptionalParams, callback: msRest.ServiceCallback<Date[] | string[]>): void;
  getDepartureDates(searchId: string, bookKey: string, arrival: Date | string, options?: Models.FuzzyAccommodationSearchGetDepartureDatesOptionalParams | msRest.ServiceCallback<Date[] | string[]>, callback?: msRest.ServiceCallback<Date[] | string[]>): Promise<Models.FuzzyAccommodationSearchGetDepartureDatesResponse> {
    return this.client.sendOperationRequest(
      {
        searchId,
        bookKey,
        arrival,
        options
      },
      getDepartureDatesOperationSpec,
      callback) as Promise<Models.FuzzyAccommodationSearchGetDepartureDatesResponse>;
  }

  /**
   * @summary Gets all departures.
   * @param searchId The search identifier.
   * @param bookKey The key representing a scan result item.
   * @param arrival The arrival.
   * @param [options] The optional parameters
   * @returns Promise<Models.FuzzyAccommodationSearchGetAllDeparturesResponse>
   */
  getAllDepartures(searchId: string, bookKey: string, arrival: Date | string, options?: Models.FuzzyAccommodationSearchGetAllDeparturesOptionalParams): Promise<Models.FuzzyAccommodationSearchGetAllDeparturesResponse>;
  /**
   * @param searchId The search identifier.
   * @param bookKey The key representing a scan result item.
   * @param arrival The arrival.
   * @param callback The callback
   */
  getAllDepartures(searchId: string, bookKey: string, arrival: Date | string, callback: msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityFuzzyAccommodationStayPeriod[]>): void;
  /**
   * @param searchId The search identifier.
   * @param bookKey The key representing a scan result item.
   * @param arrival The arrival.
   * @param options The optional parameters
   * @param callback The callback
   */
  getAllDepartures(searchId: string, bookKey: string, arrival: Date | string, options: Models.FuzzyAccommodationSearchGetAllDeparturesOptionalParams, callback: msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityFuzzyAccommodationStayPeriod[]>): void;
  getAllDepartures(searchId: string, bookKey: string, arrival: Date | string, options?: Models.FuzzyAccommodationSearchGetAllDeparturesOptionalParams | msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityFuzzyAccommodationStayPeriod[]>, callback?: msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityFuzzyAccommodationStayPeriod[]>): Promise<Models.FuzzyAccommodationSearchGetAllDeparturesResponse> {
    return this.client.sendOperationRequest(
      {
        searchId,
        bookKey,
        arrival,
        options
      },
      getAllDeparturesOperationSpec,
      callback) as Promise<Models.FuzzyAccommodationSearchGetAllDeparturesResponse>;
  }

  /**
   * @summary Gets the bookable alternatives.
   * @param searchId The search identifier.
   * @param bookKey The key representing a scan result item.
   * @param arrival The arrival.
   * @param departure The departure.
   * @param [options] The optional parameters
   * @returns Promise<Models.FuzzyAccommodationSearchGetBookableAlternativesResponse>
   */
  getBookableAlternatives(searchId: string, bookKey: string, arrival: Date | string, departure: Date | string, options?: Models.FuzzyAccommodationSearchGetBookableAlternativesOptionalParams): Promise<Models.FuzzyAccommodationSearchGetBookableAlternativesResponse>;
  /**
   * @param searchId The search identifier.
   * @param bookKey The key representing a scan result item.
   * @param arrival The arrival.
   * @param departure The departure.
   * @param callback The callback
   */
  getBookableAlternatives(searchId: string, bookKey: string, arrival: Date | string, departure: Date | string, callback: msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityFuzzyAccommodationBookableAlternative[]>): void;
  /**
   * @param searchId The search identifier.
   * @param bookKey The key representing a scan result item.
   * @param arrival The arrival.
   * @param departure The departure.
   * @param options The optional parameters
   * @param callback The callback
   */
  getBookableAlternatives(searchId: string, bookKey: string, arrival: Date | string, departure: Date | string, options: Models.FuzzyAccommodationSearchGetBookableAlternativesOptionalParams, callback: msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityFuzzyAccommodationBookableAlternative[]>): void;
  getBookableAlternatives(searchId: string, bookKey: string, arrival: Date | string, departure: Date | string, options?: Models.FuzzyAccommodationSearchGetBookableAlternativesOptionalParams | msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityFuzzyAccommodationBookableAlternative[]>, callback?: msRest.ServiceCallback<Models.GalaxyApiModelsAvailabilityFuzzyAccommodationBookableAlternative[]>): Promise<Models.FuzzyAccommodationSearchGetBookableAlternativesResponse> {
    return this.client.sendOperationRequest(
      {
        searchId,
        bookKey,
        arrival,
        departure,
        options
      },
      getBookableAlternativesOperationSpec,
      callback) as Promise<Models.FuzzyAccommodationSearchGetBookableAlternativesResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const scanOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "v3/api/availability/accommodation/fuzzy/scan",
  headerParameters: [
    Parameters.acceptLanguage
  ],
  requestBody: {
    parameterPath: "search",
    mapper: {
      ...Mappers.GalaxyApiModelsAvailabilityFuzzyAccommodationFuzzyAccommodationSearchFilter,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.GalaxyApiModelsAvailabilityFuzzyAccommodationFuzzyAccommodationSearchScanResult
    },
    default: {}
  },
  serializer
};

const getSearchOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "v3/api/availability/accommodation/fuzzy/get",
  headerParameters: [
    Parameters.acceptLanguage
  ],
  requestBody: {
    parameterPath: "query",
    mapper: {
      ...Mappers.GalaxyApiModelsSharedQueryExistingSearchQuery,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.GalaxyApiModelsAvailabilityFuzzyAccommodationFuzzyAccommodationSearchScanResult
    },
    default: {}
  },
  serializer
};

const getArrivalDatesOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "v3/api/availability/accommodation/fuzzy/arrivaldates",
  queryParameters: [
    Parameters.searchId,
    Parameters.bookKey0,
    Parameters.firstArrival,
    Parameters.lastArrival,
    Parameters.personConfigadults,
    Parameters.personConfigchildrenAges
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "DateTime"
            }
          }
        }
      }
    },
    default: {}
  },
  serializer
};

const getDepartureDatesOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "v3/api/availability/accommodation/fuzzy/departuredates",
  queryParameters: [
    Parameters.searchId,
    Parameters.bookKey0,
    Parameters.arrival,
    Parameters.personConfigadults,
    Parameters.personConfigchildrenAges
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "DateTime"
            }
          }
        }
      }
    },
    default: {}
  },
  serializer
};

const getAllDeparturesOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "v3/api/availability/accommodation/fuzzy/alldepartures",
  queryParameters: [
    Parameters.searchId,
    Parameters.bookKey0,
    Parameters.arrival,
    Parameters.personConfigadults,
    Parameters.personConfigchildrenAges
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "GalaxyApiModelsAvailabilityFuzzyAccommodationStayPeriod"
            }
          }
        }
      }
    },
    default: {}
  },
  serializer
};

const getBookableAlternativesOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "v3/api/availability/accommodation/fuzzy/bookablealternatives",
  queryParameters: [
    Parameters.searchId,
    Parameters.bookKey0,
    Parameters.arrival,
    Parameters.departure,
    Parameters.personConfigadults,
    Parameters.personConfigchildrenAges
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "GalaxyApiModelsAvailabilityFuzzyAccommodationBookableAlternative"
            }
          }
        }
      }
    },
    default: {}
  },
  serializer
};
