/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/reservationMappers";
import * as Parameters from "../models/parameters";
import { GalaxyApiContext } from "../galaxyApiContext";

/** Class representing a Reservation. */
export class Reservation {
  private readonly client: GalaxyApiContext;

  /**
   * Create a Reservation.
   * @param {GalaxyApiContext} client Reference to the service client.
   */
  constructor(client: GalaxyApiContext) {
    this.client = client;
  }

  /**
   * @summary Lists all reservation versions from booking code.
   * @param bookingCode The booking code.
   * @param [options] The optional parameters
   * @returns Promise<Models.ReservationListReservationsFromBookingCodeResponse>
   */
  listReservationsFromBookingCode(bookingCode: string, options?: msRest.RequestOptionsBase): Promise<Models.ReservationListReservationsFromBookingCodeResponse>;
  /**
   * @param bookingCode The booking code.
   * @param callback The callback
   */
  listReservationsFromBookingCode(bookingCode: string, callback: msRest.ServiceCallback<Models.GalaxyApiModelsReservationReservationFromCodeResult[]>): void;
  /**
   * @param bookingCode The booking code.
   * @param options The optional parameters
   * @param callback The callback
   */
  listReservationsFromBookingCode(bookingCode: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.GalaxyApiModelsReservationReservationFromCodeResult[]>): void;
  listReservationsFromBookingCode(bookingCode: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.GalaxyApiModelsReservationReservationFromCodeResult[]>, callback?: msRest.ServiceCallback<Models.GalaxyApiModelsReservationReservationFromCodeResult[]>): Promise<Models.ReservationListReservationsFromBookingCodeResponse> {
    return this.client.sendOperationRequest(
      {
        bookingCode,
        options
      },
      listReservationsFromBookingCodeOperationSpec,
      callback) as Promise<Models.ReservationListReservationsFromBookingCodeResponse>;
  }

  /**
   * @summary Gets the confirmation for a specific reservationVersionId
   * @param reservationVersionId The reservation version identifier.
   * @param [options] The optional parameters
   * @returns Promise<Models.ReservationGetConfirmationResponse>
   */
  getConfirmation(reservationVersionId: number, options?: msRest.RequestOptionsBase): Promise<Models.ReservationGetConfirmationResponse>;
  /**
   * @param reservationVersionId The reservation version identifier.
   * @param callback The callback
   */
  getConfirmation(reservationVersionId: number, callback: msRest.ServiceCallback<Models.GalaxyApiModelsReservationBookingConfirmation>): void;
  /**
   * @param reservationVersionId The reservation version identifier.
   * @param options The optional parameters
   * @param callback The callback
   */
  getConfirmation(reservationVersionId: number, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.GalaxyApiModelsReservationBookingConfirmation>): void;
  getConfirmation(reservationVersionId: number, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.GalaxyApiModelsReservationBookingConfirmation>, callback?: msRest.ServiceCallback<Models.GalaxyApiModelsReservationBookingConfirmation>): Promise<Models.ReservationGetConfirmationResponse> {
    return this.client.sendOperationRequest(
      {
        reservationVersionId,
        options
      },
      getConfirmationOperationSpec,
      callback) as Promise<Models.ReservationGetConfirmationResponse>;
  }

  /**
   * @summary Gets the latest confirmation for the specfied booking code.
   * @param bookingCode The booking code.
   * @param [options] The optional parameters
   * @returns Promise<Models.ReservationGetLatestConfirmationResponse>
   */
  getLatestConfirmation(bookingCode: string, options?: msRest.RequestOptionsBase): Promise<Models.ReservationGetLatestConfirmationResponse>;
  /**
   * @param bookingCode The booking code.
   * @param callback The callback
   */
  getLatestConfirmation(bookingCode: string, callback: msRest.ServiceCallback<Models.GalaxyApiModelsReservationBookingConfirmation>): void;
  /**
   * @param bookingCode The booking code.
   * @param options The optional parameters
   * @param callback The callback
   */
  getLatestConfirmation(bookingCode: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.GalaxyApiModelsReservationBookingConfirmation>): void;
  getLatestConfirmation(bookingCode: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.GalaxyApiModelsReservationBookingConfirmation>, callback?: msRest.ServiceCallback<Models.GalaxyApiModelsReservationBookingConfirmation>): Promise<Models.ReservationGetLatestConfirmationResponse> {
    return this.client.sendOperationRequest(
      {
        bookingCode,
        options
      },
      getLatestConfirmationOperationSpec,
      callback) as Promise<Models.ReservationGetLatestConfirmationResponse>;
  }

  /**
   * @summary Start a cancellation job for the latest version of the specified bookingCode. Check
   * QueryCommitStatus for the progress.
   * @param bookingCode The booking code.
   * @param [options] The optional parameters
   * @returns Promise<Models.ReservationCancelBookingResponse>
   */
  cancelBooking(bookingCode: string, options?: msRest.RequestOptionsBase): Promise<Models.ReservationCancelBookingResponse>;
  /**
   * @param bookingCode The booking code.
   * @param callback The callback
   */
  cancelBooking(bookingCode: string, callback: msRest.ServiceCallback<number>): void;
  /**
   * @param bookingCode The booking code.
   * @param options The optional parameters
   * @param callback The callback
   */
  cancelBooking(bookingCode: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<number>): void;
  cancelBooking(bookingCode: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<number>, callback?: msRest.ServiceCallback<number>): Promise<Models.ReservationCancelBookingResponse> {
    return this.client.sendOperationRequest(
      {
        bookingCode,
        options
      },
      cancelBookingOperationSpec,
      callback) as Promise<Models.ReservationCancelBookingResponse>;
  }

  /**
   * @summary Get information about the cancellation of a booking.
   * @param bookingCode The booking code.
   * @param [options] The optional parameters
   * @deprecated This operation is deprecated. Please do not use it any longer.
   * @returns Promise<Models.ReservationGetCancellationInformationResponse>
   */
  getCancellationInformation(bookingCode: string, options?: msRest.RequestOptionsBase): Promise<Models.ReservationGetCancellationInformationResponse>;
  /**
   * @param bookingCode The booking code.
   * @param callback The callback
   * @deprecated This operation is deprecated. Please do not use it any longer.
   */
  getCancellationInformation(bookingCode: string, callback: msRest.ServiceCallback<Models.GalaxyApiModelsReservationCancellationInformation>): void;
  /**
   * @param bookingCode The booking code.
   * @param options The optional parameters
   * @param callback The callback
   * @deprecated This operation is deprecated. Please do not use it any longer.
   */
  getCancellationInformation(bookingCode: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.GalaxyApiModelsReservationCancellationInformation>): void;
  getCancellationInformation(bookingCode: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.GalaxyApiModelsReservationCancellationInformation>, callback?: msRest.ServiceCallback<Models.GalaxyApiModelsReservationCancellationInformation>): Promise<Models.ReservationGetCancellationInformationResponse> {
    return this.client.sendOperationRequest(
      {
        bookingCode,
        options
      },
      getCancellationInformationOperationSpec,
      callback) as Promise<Models.ReservationGetCancellationInformationResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const listReservationsFromBookingCodeOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "v3/api/reservation/{bookingCode}",
  urlParameters: [
    Parameters.bookingCode
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "GalaxyApiModelsReservationReservationFromCodeResult"
            }
          }
        }
      }
    },
    default: {}
  },
  serializer
};

const getConfirmationOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "v3/api/reservation/version/{reservationVersionId}",
  urlParameters: [
    Parameters.reservationVersionId
  ],
  responses: {
    200: {
      bodyMapper: Mappers.GalaxyApiModelsReservationBookingConfirmation
    },
    default: {}
  },
  serializer
};

const getLatestConfirmationOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "v3/api/reservation/latest/{bookingCode}",
  urlParameters: [
    Parameters.bookingCode
  ],
  responses: {
    200: {
      bodyMapper: Mappers.GalaxyApiModelsReservationBookingConfirmation
    },
    default: {}
  },
  serializer
};

const cancelBookingOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "v3/api/reservation/cancel/{bookingCode}",
  urlParameters: [
    Parameters.bookingCode
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Number"
        }
      }
    },
    default: {}
  },
  serializer
};

const getCancellationInformationOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "v3/api/reservation/cancel/info/{bookingCode}",
  urlParameters: [
    Parameters.bookingCode
  ],
  responses: {
    200: {
      bodyMapper: Mappers.GalaxyApiModelsReservationCancellationInformation
    },
    default: {}
  },
  serializer
};
