/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";

export const acceptLanguage: msRest.OperationParameter = {
  parameterPath: "acceptLanguage",
  mapper: {
    required: true,
    serializedName: "Accept-Language",
    type: {
      name: "String"
    }
  }
};
export const arrival: msRest.OperationQueryParameter = {
  parameterPath: "arrival",
  mapper: {
    required: true,
    serializedName: "arrival",
    type: {
      name: "DateTime"
    }
  }
};
export const basketId: msRest.OperationURLParameter = {
  parameterPath: "basketId",
  mapper: {
    required: true,
    serializedName: "basketId",
    type: {
      name: "Number"
    }
  }
};
export const bookingCode: msRest.OperationURLParameter = {
  parameterPath: "bookingCode",
  mapper: {
    required: true,
    serializedName: "bookingCode",
    type: {
      name: "String"
    }
  }
};
export const bookItemId: msRest.OperationURLParameter = {
  parameterPath: "bookItemId",
  mapper: {
    required: true,
    serializedName: "bookItemId",
    type: {
      name: "Number"
    }
  }
};
export const bookKey0: msRest.OperationQueryParameter = {
  parameterPath: "bookKey",
  mapper: {
    required: true,
    serializedName: "bookKey",
    type: {
      name: "String"
    }
  }
};
export const bookKey1: msRest.OperationURLParameter = {
  parameterPath: "bookKey",
  mapper: {
    required: true,
    serializedName: "bookKey",
    type: {
      name: "Number"
    }
  }
};
export const cancellationId: msRest.OperationURLParameter = {
  parameterPath: "cancellationId",
  mapper: {
    required: true,
    serializedName: "cancellationId",
    type: {
      name: "Number"
    }
  }
};
export const countryCodeId: msRest.OperationURLParameter = {
  parameterPath: "countryCodeId",
  mapper: {
    required: true,
    serializedName: "countryCodeId",
    type: {
      name: "String"
    }
  }
};
export const departure: msRest.OperationQueryParameter = {
  parameterPath: "departure",
  mapper: {
    required: true,
    serializedName: "departure",
    type: {
      name: "DateTime"
    }
  }
};
export const firstArrival: msRest.OperationQueryParameter = {
  parameterPath: "firstArrival",
  mapper: {
    required: true,
    serializedName: "firstArrival",
    type: {
      name: "DateTime"
    }
  }
};
export const guestId: msRest.OperationURLParameter = {
  parameterPath: "guestId",
  mapper: {
    required: true,
    serializedName: "guestId",
    type: {
      name: "Number"
    }
  }
};
export const id: msRest.OperationURLParameter = {
  parameterPath: "id",
  mapper: {
    required: true,
    serializedName: "id",
    type: {
      name: "Number"
    }
  }
};
export const lastArrival: msRest.OperationQueryParameter = {
  parameterPath: "lastArrival",
  mapper: {
    required: true,
    serializedName: "lastArrival",
    type: {
      name: "DateTime"
    }
  }
};
export const online3Id: msRest.OperationQueryParameter = {
  parameterPath: "online3Id",
  mapper: {
    required: true,
    serializedName: "online3Id",
    type: {
      name: "Number"
    }
  }
};
export const online3Session: msRest.OperationQueryParameter = {
  parameterPath: "online3Session",
  mapper: {
    required: true,
    serializedName: "online3Session",
    type: {
      name: "String"
    }
  }
};
export const page: msRest.OperationURLParameter = {
  parameterPath: "page",
  mapper: {
    required: true,
    serializedName: "page",
    type: {
      name: "Number"
    }
  }
};
export const pageSize: msRest.OperationURLParameter = {
  parameterPath: "pageSize",
  mapper: {
    required: true,
    serializedName: "pageSize",
    type: {
      name: "Number"
    }
  }
};
export const personConfigadults: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "personConfigadults"
  ],
  mapper: {
    serializedName: "personConfig.adults",
    type: {
      name: "Number"
    }
  }
};
export const personConfigchildrenAges: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "personConfigchildrenAges"
  ],
  mapper: {
    serializedName: "personConfig.childrenAges",
    type: {
      name: "Sequence",
      element: {
        type: {
          name: "Number"
        }
      }
    }
  },
  collectionFormat: msRest.QueryCollectionFormat.Multi
};
export const pointOfSalesId: msRest.OperationURLParameter = {
  parameterPath: "pointOfSalesId",
  mapper: {
    required: true,
    serializedName: "pointOfSalesId",
    type: {
      name: "Number"
    }
  }
};
export const productId: msRest.OperationURLParameter = {
  parameterPath: "productId",
  mapper: {
    required: true,
    serializedName: "productId",
    type: {
      name: "String"
    }
  }
};
export const reservationVersionId: msRest.OperationURLParameter = {
  parameterPath: "reservationVersionId",
  mapper: {
    required: true,
    serializedName: "reservationVersionId",
    type: {
      name: "Number"
    }
  }
};
export const searchId: msRest.OperationQueryParameter = {
  parameterPath: "searchId",
  mapper: {
    required: true,
    serializedName: "searchId",
    type: {
      name: "String"
    }
  }
};
export const state: msRest.OperationURLParameter = {
  parameterPath: "state",
  mapper: {
    required: true,
    serializedName: "state",
    type: {
      name: "Boolean"
    }
  }
};
